### ISSUE TITLE
Domain name used for API call is expired

### ISSUE THREAD

**Issue by ghost** [alQuranBD/Bangla-Hadith-api#1]
The domain name "alquranbd.com" may has been expired on 2022-06-13 (20:03:21). So fetching any of URI of your API is failing now though it was working fine before. I request to solve the problem and let me use your API. Thanks for building such an API.
The screenshot of the page at "alquranbd.com/api/hadith/bukhari" is given below:
![screencapture-alquranbd-api-hadith-bukhari-2022-07-05-15_43_05](https://user-images.githubusercontent.com/108727798/177300150-2b902794-7d26-4b9c-90c2-4668a9ec8e61.jpg)

**Comment by niamulhasan** [comment]
Thank you for notifying that. Looking into the problem

**Comment by niamulhasan** [comment]
The issue is solved
